<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AntFarm.Chinese.Domain\AntFarm.Chinese.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\shared\AntFarm.Core\AntFarm.Core.csproj" />
  </ItemGroup>

</Project>
