// <auto-generated />
using System;
using System.Collections.Generic;
using AntFarm.Chinese.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AntFarm.Chinese.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChineseDbContext))]
    [Migration("20260916232634_F7_Srs")]
    partial class F7_Srs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.HasKey("Code")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "access");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_code");

                    b.ToTable("roles", "access");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission_code");

                    b.HasKey("RoleId", "PermissionCode")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionCode")
                        .HasDatabaseName("ix_role_permissions_permission_code");

                    b.ToTable("role_permissions", "access");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("EmailLower")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("email_lower")
                        .HasComputedColumnSql("lower(email)", true);

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EmailLower")
                        .HasDatabaseName("ix_users_email_lower");

                    b.ToTable("users", "access");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "access");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Content.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.PrimitiveCollection<List<string>>("HanViet")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("han_viet");

                    b.Property<string>("HanVietByPinyin")
                        .HasColumnType("jsonb")
                        .HasColumnName("han_viet_by_pinyin");

                    b.Property<string>("HanVietStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("han_viet_status");

                    b.Property<string>("Hanzi")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("hanzi");

                    b.PrimitiveCollection<List<string>>("PinyinReadings")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("pinyin_readings");

                    b.Property<string>("Radical")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("radical");

                    b.Property<short?>("RadicalNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("radical_number");

                    b.PrimitiveCollection<List<string>>("Sources")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("sources");

                    b.Property<short?>("StrokeCount")
                        .HasColumnType("smallint")
                        .HasColumnName("stroke_count");

                    b.PrimitiveCollection<List<string>>("TraditionalVariants")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("traditional_variants");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("Hanzi")
                        .IsUnique()
                        .HasDatabaseName("ux_characters_hanzi");

                    b.ToTable("characters", "content", t =>
                        {
                            t.HasCheckConstraint("ck_characters_han_viet_status", "han_viet_status IN ('derived','reviewed')");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Content.ImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Dataset")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("dataset");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_hash");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("ImporterVersion")
                        .HasColumnType("integer")
                        .HasColumnName("importer_version");

                    b.Property<int>("Inserted")
                        .HasColumnType("integer")
                        .HasColumnName("inserted");

                    b.Property<int>("Invalid")
                        .HasColumnType("integer")
                        .HasColumnName("invalid");

                    b.Property<int>("Protected")
                        .HasColumnType("integer")
                        .HasColumnName("protected");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("Unchanged")
                        .HasColumnType("integer")
                        .HasColumnName("unchanged");

                    b.Property<int>("Updated")
                        .HasColumnType("integer")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_import_runs");

                    b.HasIndex("Dataset", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_import_runs_dataset_started");

                    b.ToTable("import_runs", "content", t =>
                        {
                            t.HasCheckConstraint("ck_import_runs_status", "status IN ('succeeded','failed')");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Content.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<Guid?>("EditedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("edited_by");

                    b.Property<int?>("FrequencyRank")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_rank");

                    b.Property<string>("HanViet")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("han_viet");

                    b.Property<string>("HanVietPlain")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("han_viet_plain");

                    b.Property<string>("HanVietStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("han_viet_status");

                    b.Property<short?>("Hsk2Level")
                        .HasColumnType("smallint")
                        .HasColumnName("hsk2_level");

                    b.Property<short?>("Hsk3Level")
                        .HasColumnType("smallint")
                        .HasColumnName("hsk3_level");

                    b.Property<short?>("HskExam2026Level")
                        .HasColumnType("smallint")
                        .HasColumnName("hsk_exam2026_level");

                    b.Property<string>("MeaningViSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("meaning_vi_source");

                    b.Property<string>("MeaningViStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("meaning_vi_status");

                    b.PrimitiveCollection<List<string>>("MeaningsEn")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("meanings_en");

                    b.PrimitiveCollection<List<string>>("MeaningsVi")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("meanings_vi");

                    b.Property<short?>("OfficialIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("official_index");

                    b.Property<int?>("PathOrder")
                        .HasColumnType("integer")
                        .HasColumnName("path_order");

                    b.Property<string>("Pinyin")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pinyin");

                    b.Property<string>("PinyinCompact")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pinyin_compact");

                    b.Property<string>("PinyinSearch")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pinyin_search");

                    b.PrimitiveCollection<List<string>>("Pos")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("pos");

                    b.Property<string>("SearchVi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_vi");

                    b.Property<string>("SearchViPlain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_vi_plain");

                    b.Property<string>("Simplified")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("simplified");

                    b.PrimitiveCollection<List<string>>("Sources")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("sources");

                    b.Property<string>("Traditional")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("traditional");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsageNote")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("usage_note");

                    b.PrimitiveCollection<List<string>>("Variants")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("variants");

                    b.HasKey("Id")
                        .HasName("pk_words");

                    b.HasIndex("HanVietPlain")
                        .HasDatabaseName("ix_words_han_viet_plain");

                    b.HasIndex("Hsk2Level")
                        .HasDatabaseName("ix_words_hsk2");

                    b.HasIndex("PinyinCompact")
                        .HasDatabaseName("ix_words_pinyin_compact");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("PinyinCompact"), new[] { "varchar_pattern_ops" });

                    b.HasIndex("PinyinSearch")
                        .HasDatabaseName("ix_words_pinyin_search");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("PinyinSearch"), new[] { "varchar_pattern_ops" });

                    b.HasIndex("SearchVi")
                        .HasDatabaseName("ix_words_search_vi_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVi"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchVi"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SearchViPlain")
                        .HasDatabaseName("ix_words_search_vi_plain_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchViPlain"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchViPlain"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Simplified")
                        .HasDatabaseName("ix_words_simplified_pattern");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Simplified"), new[] { "varchar_pattern_ops" });

                    b.HasIndex("Traditional")
                        .HasDatabaseName("ix_words_traditional");

                    b.HasIndex("Hsk3Level", "PathOrder")
                        .HasDatabaseName("ix_words_level_path");

                    b.HasIndex("Simplified", "Pinyin")
                        .IsUnique()
                        .HasDatabaseName("ux_words_simplified_pinyin");

                    b.ToTable("words", "content", t =>
                        {
                            t.HasCheckConstraint("ck_words_han_viet_status", "han_viet_status IS NULL OR han_viet_status IN ('derived','reviewed')");

                            t.HasCheckConstraint("ck_words_hsk2_level", "hsk2_level IS NULL OR hsk2_level BETWEEN 1 AND 6");

                            t.HasCheckConstraint("ck_words_hsk3_level", "hsk3_level IS NULL OR hsk3_level BETWEEN 1 AND 7");

                            t.HasCheckConstraint("ck_words_hsk_exam2026_level", "hsk_exam2026_level IS NULL OR hsk_exam2026_level BETWEEN 1 AND 7");

                            t.HasCheckConstraint("ck_words_meaning_vi_source", "meaning_vi_source IN ('cvdict','machine','manual')");

                            t.HasCheckConstraint("ck_words_meaning_vi_status", "meaning_vi_status IN ('machine','reviewed')");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Content.WordCharacter", b =>
                {
                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.Property<short>("Position")
                        .HasColumnType("smallint")
                        .HasColumnName("position");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.HasKey("WordId", "Position")
                        .HasName("pk_word_characters");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_word_characters_character");

                    b.ToTable("word_characters", "content");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.LearnerSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("AutoPlayAudio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_play_audio");

                    b.Property<short>("DailyNewCards")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)10)
                        .HasColumnName("daily_new_cards");

                    b.Property<short>("DailyReviewLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)200)
                        .HasColumnName("daily_review_limit");

                    b.Property<decimal>("DesiredRetention")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0.90m)
                        .HasColumnName("desired_retention");

                    b.Property<decimal>("TtsRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0.80m)
                        .HasColumnName("tts_rate");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_learner_settings");

                    b.ToTable("learner_settings", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_learner_settings_daily_new_cards", "daily_new_cards BETWEEN 0 AND 50");

                            t.HasCheckConstraint("ck_learner_settings_daily_review_limit", "daily_review_limit BETWEEN 10 AND 1000");

                            t.HasCheckConstraint("ck_learner_settings_desired_retention", "desired_retention BETWEEN 0.80 AND 0.97");

                            t.HasCheckConstraint("ck_learner_settings_tts_rate", "tts_rate BETWEEN 0.50 AND 1.20");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.StudyEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Correct")
                        .HasColumnType("integer")
                        .HasColumnName("correct");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_study_events");

                    b.HasIndex("UserId", "LocalDate")
                        .HasDatabaseName("ix_study_events_user_id_local_date");

                    b.HasIndex("UserId", "Kind", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_study_events_user_id_kind_occurred_at");

                    b.ToTable("study_events", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_study_events_correct", "correct IS NULL OR (correct >= 0 AND correct <= quantity)");

                            t.HasCheckConstraint("ck_study_events_quantity", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Pinyin.ToneDrillAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<short>("AnsweredTone")
                        .HasColumnType("smallint")
                        .HasColumnName("answered_tone");

                    b.Property<short>("ExpectedTone")
                        .HasColumnType("smallint")
                        .HasColumnName("expected_tone");

                    b.Property<string>("Hanzi")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("hanzi");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<short>("ItemIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("item_index");

                    b.Property<short>("PartIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("part_index");

                    b.Property<short>("ReplayCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("replay_count");

                    b.Property<int?>("ResponseMs")
                        .HasColumnType("integer")
                        .HasColumnName("response_ms");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Syllable")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("syllable");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tone_drill_answers");

                    b.HasIndex("SessionId", "ItemIndex", "PartIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_tone_drill_answers_session_id_item_index_part_index");

                    b.HasIndex("UserId", "ExpectedTone", "AnsweredAt", "PartIndex")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_tone_drill_answers_user_id_expected_tone_answered_at_part_i");

                    b.ToTable("tone_drill_answers", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_tone_drill_answers_answered_tone", "answered_tone BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_tone_drill_answers_expected_tone", "expected_tone BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_tone_drill_answers_item_index", "item_index >= 0");

                            t.HasCheckConstraint("ck_tone_drill_answers_part_index", "part_index IN (0,1)");

                            t.HasCheckConstraint("ck_tone_drill_answers_replay_count", "replay_count BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_tone_drill_answers_response_ms", "response_ms IS NULL OR response_ms BETWEEN 0 AND 600000");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Pinyin.ToneDrillSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_session_id");

                    b.Property<short>("Correct")
                        .HasColumnType("smallint")
                        .HasColumnName("correct");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("Total")
                        .HasColumnType("smallint")
                        .HasColumnName("total");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tone_drill_sessions");

                    b.HasIndex("UserId", "ClientSessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_tone_drill_sessions_user_id_client_session_id");

                    b.HasIndex("UserId", "FinishedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_tone_drill_sessions_user_id_finished_at");

                    b.ToTable("tone_drill_sessions", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_tone_drill_sessions_correct", "correct BETWEEN 0 AND total");

                            t.HasCheckConstraint("ck_tone_drill_sessions_finished_after_started", "finished_at >= started_at");

                            t.HasCheckConstraint("ck_tone_drill_sessions_mode", "mode IN ('listen_tone','tone_pair')");

                            t.HasCheckConstraint("ck_tone_drill_sessions_total", "total BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Srs.SrsCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasDefaultValue("hanzi_to_meaning")
                        .HasColumnName("card_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("Difficulty")
                        .HasColumnType("double precision")
                        .HasColumnName("difficulty");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<DateTime?>("FirstReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_reviewed_at");

                    b.Property<DateOnly?>("FirstReviewedLocalDate")
                        .HasColumnType("date")
                        .HasColumnName("first_reviewed_local_date");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suspended");

                    b.Property<int>("Lapses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("lapses");

                    b.Property<DateTime?>("LastReviewAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_review_at");

                    b.Property<int>("Reps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reps");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("source");

                    b.Property<double?>("Stability")
                        .HasColumnType("double precision")
                        .HasColumnName("stability");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("state");

                    b.Property<short?>("Step")
                        .HasColumnType("smallint")
                        .HasColumnName("step");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.HasKey("Id")
                        .HasName("pk_srs_cards");

                    b.HasIndex("WordId")
                        .HasDatabaseName("ix_srs_cards_word_id");

                    b.HasIndex("UserId", "FirstReviewedLocalDate")
                        .HasDatabaseName("ix_srs_cards_user_first_date");

                    b.HasIndex("UserId", "State", "DueAt")
                        .HasDatabaseName("ix_srs_cards_user_state_due")
                        .HasFilter("is_suspended = false");

                    b.HasIndex("UserId", "WordId", "CardType")
                        .IsUnique()
                        .HasDatabaseName("ux_srs_cards_user_word_type");

                    b.ToTable("srs_cards", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_srs_cards_card_type", "card_type IN ('hanzi_to_meaning')");

                            t.HasCheckConstraint("ck_srs_cards_source", "source IN ('path','manual','lesson')");

                            t.HasCheckConstraint("ck_srs_cards_state", "state IN ('new','learning','review','relearning')");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Srs.SrsReviewLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<Guid>("ClientReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_review_id");

                    b.Property<double>("DifficultyAfter")
                        .HasColumnType("double precision")
                        .HasColumnName("difficulty_after");

                    b.Property<double?>("DifficultyBefore")
                        .HasColumnType("double precision")
                        .HasColumnName("difficulty_before");

                    b.Property<DateTime>("DueAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_after");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<double>("ElapsedDays")
                        .HasColumnType("double precision")
                        .HasColumnName("elapsed_days");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<double>("ScheduledDays")
                        .HasColumnType("double precision")
                        .HasColumnName("scheduled_days");

                    b.Property<double>("StabilityAfter")
                        .HasColumnType("double precision")
                        .HasColumnName("stability_after");

                    b.Property<double?>("StabilityBefore")
                        .HasColumnType("double precision")
                        .HasColumnName("stability_before");

                    b.Property<string>("StateAfter")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("state_after");

                    b.Property<string>("StateBefore")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("state_before");

                    b.Property<short?>("StepBefore")
                        .HasColumnType("smallint")
                        .HasColumnName("step_before");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_srs_review_logs");

                    b.HasIndex("ClientReviewId")
                        .IsUnique()
                        .HasDatabaseName("ux_srs_review_logs_client_review_id");

                    b.HasIndex("CardId", "ReviewedAt")
                        .HasDatabaseName("ix_srs_review_logs_card");

                    b.HasIndex("UserId", "LocalDate")
                        .HasDatabaseName("ix_srs_review_logs_user_date");

                    b.ToTable("srs_review_logs", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_srs_review_logs_rating", "rating BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.RolePermission", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_code");

                    b.HasOne("AntFarm.Chinese.Domain.Access.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.UserRole", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Content.WordCharacter", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Content.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_word_characters_characters_character_id");

                    b.HasOne("AntFarm.Chinese.Domain.Content.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_characters_words_word_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.LearnerSettings", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithOne()
                        .HasForeignKey("AntFarm.Chinese.Domain.Learning.LearnerSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learner_settings_users_user_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.StudyEvent", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_study_events_users_user_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Pinyin.ToneDrillAnswer", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Pinyin.ToneDrillSession", null)
                        .WithMany("Answers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tone_drill_answers_tone_drill_sessions_session_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Pinyin.ToneDrillSession", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tone_drill_sessions_users_user_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Srs.SrsCard", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_srs_cards_users_user_id");

                    b.HasOne("AntFarm.Chinese.Domain.Content.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_srs_cards_words_word_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Srs.SrsReviewLog", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Srs.SrsCard", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_srs_review_logs_srs_cards_card_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Pinyin.ToneDrillSession", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
