// <auto-generated />
using System;
using System.Collections.Generic;
using AntFarm.Chinese.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AntFarm.Chinese.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChineseDbContext))]
    partial class ChineseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.HasKey("Code")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "access");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_code");

                    b.ToTable("roles", "access");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission_code");

                    b.HasKey("RoleId", "PermissionCode")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionCode")
                        .HasDatabaseName("ix_role_permissions_permission_code");

                    b.ToTable("role_permissions", "access");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("EmailLower")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("email_lower")
                        .HasComputedColumnSql("lower(email)", true);

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EmailLower")
                        .HasDatabaseName("ix_users_email_lower");

                    b.ToTable("users", "access");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "access");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Content.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.PrimitiveCollection<List<string>>("HanViet")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("han_viet");

                    b.Property<string>("HanVietByPinyin")
                        .HasColumnType("jsonb")
                        .HasColumnName("han_viet_by_pinyin");

                    b.Property<string>("HanVietStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("han_viet_status");

                    b.Property<string>("Hanzi")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("hanzi");

                    b.PrimitiveCollection<List<string>>("PinyinReadings")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("pinyin_readings");

                    b.Property<string>("Radical")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("radical");

                    b.Property<short?>("RadicalNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("radical_number");

                    b.PrimitiveCollection<List<string>>("Sources")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("sources");

                    b.Property<short?>("StrokeCount")
                        .HasColumnType("smallint")
                        .HasColumnName("stroke_count");

                    b.PrimitiveCollection<List<string>>("TraditionalVariants")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("traditional_variants");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasAlternateKey("Hanzi")
                        .HasName("ak_characters_hanzi");

                    b.ToTable("characters", "content", t =>
                        {
                            t.HasCheckConstraint("ck_characters_han_viet_status", "han_viet_status IN ('derived','reviewed')");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Content.ImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Dataset")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("dataset");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_hash");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("ImporterVersion")
                        .HasColumnType("integer")
                        .HasColumnName("importer_version");

                    b.Property<int>("Inserted")
                        .HasColumnType("integer")
                        .HasColumnName("inserted");

                    b.Property<int>("Invalid")
                        .HasColumnType("integer")
                        .HasColumnName("invalid");

                    b.Property<int>("Protected")
                        .HasColumnType("integer")
                        .HasColumnName("protected");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<int>("Unchanged")
                        .HasColumnType("integer")
                        .HasColumnName("unchanged");

                    b.Property<int>("Updated")
                        .HasColumnType("integer")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_import_runs");

                    b.HasIndex("Dataset", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_import_runs_dataset_started");

                    b.ToTable("import_runs", "content", t =>
                        {
                            t.HasCheckConstraint("ck_import_runs_status", "status IN ('succeeded','failed')");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Content.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<Guid?>("EditedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("edited_by");

                    b.Property<int?>("FrequencyRank")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_rank");

                    b.Property<string>("HanViet")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("han_viet");

                    b.Property<string>("HanVietPlain")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("han_viet_plain");

                    b.Property<string>("HanVietStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("han_viet_status");

                    b.Property<short?>("Hsk2Level")
                        .HasColumnType("smallint")
                        .HasColumnName("hsk2_level");

                    b.Property<short?>("Hsk3Level")
                        .HasColumnType("smallint")
                        .HasColumnName("hsk3_level");

                    b.Property<short?>("HskExam2026Level")
                        .HasColumnType("smallint")
                        .HasColumnName("hsk_exam2026_level");

                    b.Property<string>("MeaningViSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("meaning_vi_source");

                    b.Property<string>("MeaningViStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("meaning_vi_status");

                    b.PrimitiveCollection<List<string>>("MeaningsEn")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("meanings_en");

                    b.PrimitiveCollection<List<string>>("MeaningsVi")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("meanings_vi");

                    b.Property<short?>("OfficialIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("official_index");

                    b.Property<int?>("PathOrder")
                        .HasColumnType("integer")
                        .HasColumnName("path_order");

                    b.Property<string>("Pinyin")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pinyin");

                    b.Property<string>("PinyinCompact")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pinyin_compact");

                    b.Property<string>("PinyinSearch")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pinyin_search");

                    b.PrimitiveCollection<List<string>>("Pos")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("pos");

                    b.Property<string>("SearchVi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_vi");

                    b.Property<string>("SearchViPlain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_vi_plain");

                    b.Property<string>("Simplified")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("simplified");

                    b.PrimitiveCollection<List<string>>("Sources")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("sources");

                    b.Property<string>("Traditional")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("traditional");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsageNote")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("usage_note");

                    b.PrimitiveCollection<List<string>>("Variants")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("variants");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_words");

                    b.HasIndex("HanVietPlain")
                        .HasDatabaseName("ix_words_han_viet_plain");

                    b.HasIndex("Hsk2Level")
                        .HasDatabaseName("ix_words_hsk2");

                    b.HasIndex("PinyinCompact")
                        .HasDatabaseName("ix_words_pinyin_compact");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("PinyinCompact"), new[] { "varchar_pattern_ops" });

                    b.HasIndex("PinyinSearch")
                        .HasDatabaseName("ix_words_pinyin_search");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("PinyinSearch"), new[] { "varchar_pattern_ops" });

                    b.HasIndex("SearchVi")
                        .HasDatabaseName("ix_words_search_vi_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVi"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchVi"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SearchViPlain")
                        .HasDatabaseName("ix_words_search_vi_plain_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchViPlain"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchViPlain"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Simplified")
                        .HasDatabaseName("ix_words_simplified_pattern");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Simplified"), new[] { "varchar_pattern_ops" });

                    b.HasIndex("Traditional")
                        .HasDatabaseName("ix_words_traditional");

                    b.HasIndex("Hsk3Level", "PathOrder")
                        .HasDatabaseName("ix_words_level_path");

                    b.HasIndex("Simplified", "Pinyin")
                        .IsUnique()
                        .HasDatabaseName("ux_words_simplified_pinyin");

                    b.HasIndex("MeaningViStatus", "Hsk3Level", "PathOrder")
                        .HasDatabaseName("ix_words_review");

                    b.ToTable("words", "content", t =>
                        {
                            t.HasCheckConstraint("ck_words_han_viet_status", "han_viet_status IS NULL OR han_viet_status IN ('derived','reviewed')");

                            t.HasCheckConstraint("ck_words_hsk2_level", "hsk2_level IS NULL OR hsk2_level BETWEEN 1 AND 6");

                            t.HasCheckConstraint("ck_words_hsk3_level", "hsk3_level IS NULL OR hsk3_level BETWEEN 1 AND 7");

                            t.HasCheckConstraint("ck_words_hsk_exam2026_level", "hsk_exam2026_level IS NULL OR hsk_exam2026_level BETWEEN 1 AND 7");

                            t.HasCheckConstraint("ck_words_meaning_vi_source", "meaning_vi_source IN ('cvdict','machine','manual')");

                            t.HasCheckConstraint("ck_words_meaning_vi_status", "meaning_vi_status IN ('machine','reviewed')");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Content.WordCharacter", b =>
                {
                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.Property<short>("Position")
                        .HasColumnType("smallint")
                        .HasColumnName("position");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.HasKey("WordId", "Position")
                        .HasName("pk_word_characters");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_word_characters_character");

                    b.ToTable("word_characters", "content");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.CharacterWritingStats", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Hanzi")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("hanzi");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<short?>("BestRecallMistakes")
                        .HasColumnType("smallint")
                        .HasColumnName("best_recall_mistakes");

                    b.Property<short>("CleanRecallDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("clean_recall_days");

                    b.Property<DateTime>("FirstPracticedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_practiced_at");

                    b.Property<int>("GuidedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("guided_attempts");

                    b.Property<DateOnly?>("LastCleanRecallDate")
                        .HasColumnType("date")
                        .HasColumnName("last_clean_recall_date");

                    b.Property<short>("LastHints")
                        .HasColumnType("smallint")
                        .HasColumnName("last_hints");

                    b.Property<short>("LastMistakes")
                        .HasColumnType("smallint")
                        .HasColumnName("last_mistakes");

                    b.Property<string>("LastMode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("last_mode");

                    b.Property<DateTime>("LastPracticedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_practiced_at");

                    b.Property<int>("RecallAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("recall_attempts");

                    b.HasKey("UserId", "Hanzi")
                        .HasName("pk_character_writing_stats");

                    b.HasIndex("Hanzi")
                        .HasDatabaseName("ix_character_writing_stats_hanzi");

                    b.HasIndex("UserId", "LastPracticedAt")
                        .HasDatabaseName("ix_char_writing_stats_user_last");

                    b.ToTable("character_writing_stats", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_char_writing_stats_last_mode", "last_mode IN ('guided','recall')");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.LearnerSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("AutoPlayAudio")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_play_audio");

                    b.Property<short>("DailyNewCards")
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)10)
                        .HasColumnName("daily_new_cards");

                    b.Property<short>("DailyReviewLimit")
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)200)
                        .HasColumnName("daily_review_limit");

                    b.Property<decimal>("DesiredRetention")
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0.90m)
                        .HasColumnName("desired_retention");

                    b.Property<decimal>("TtsRate")
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0.80m)
                        .HasColumnName("tts_rate");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_learner_settings");

                    b.ToTable("learner_settings", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_learner_settings_daily_new_cards", "daily_new_cards BETWEEN 0 AND 50");

                            t.HasCheckConstraint("ck_learner_settings_daily_review_limit", "daily_review_limit BETWEEN 10 AND 1000");

                            t.HasCheckConstraint("ck_learner_settings_desired_retention", "desired_retention BETWEEN 0.80 AND 0.97");

                            t.HasCheckConstraint("ck_learner_settings_tts_rate", "tts_rate BETWEEN 0.50 AND 1.20");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.LessonProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<int>("AttemptsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts_count");

                    b.Property<short?>("BestScorePercent")
                        .HasColumnType("smallint")
                        .HasColumnName("best_score_percent");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "LessonId")
                        .HasName("pk_lesson_progress");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_lesson_progress_lesson_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_lesson_progress_user_status");

                    b.ToTable("lesson_progress", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_lesson_progress_best_score", "best_score_percent IS NULL OR best_score_percent BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_lesson_progress_status", "status IN ('in_progress','completed')");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answers");

                    b.Property<Guid>("ClientAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_attempt_id");

                    b.Property<short>("Correct")
                        .HasColumnType("smallint")
                        .HasColumnName("correct");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<short>("ScorePercent")
                        .HasColumnType("smallint")
                        .HasColumnName("score_percent");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<short>("Total")
                        .HasColumnType("smallint")
                        .HasColumnName("total");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_quiz_attempts");

                    b.HasIndex("ClientAttemptId")
                        .IsUnique()
                        .HasDatabaseName("ux_quiz_attempts_client_attempt_id");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_quiz_attempts_lesson_id");

                    b.HasIndex("UserId", "LessonId", "SubmittedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_quiz_attempts_user_lesson");

                    b.ToTable("quiz_attempts", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_quiz_attempts_correct", "correct BETWEEN 0 AND total");

                            t.HasCheckConstraint("ck_quiz_attempts_score_percent", "score_percent BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_quiz_attempts_total", "total > 0");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.StudyEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Correct")
                        .HasColumnType("integer")
                        .HasColumnName("correct");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_study_events");

                    b.HasIndex("UserId", "LocalDate")
                        .HasDatabaseName("ix_study_events_user_id_local_date");

                    b.HasIndex("UserId", "Kind", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_study_events_user_id_kind_occurred_at");

                    b.ToTable("study_events", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_study_events_correct", "correct IS NULL OR (correct >= 0 AND correct <= quantity)");

                            t.HasCheckConstraint("ck_study_events_quantity", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.WritingAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_attempt_id");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Hanzi")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("hanzi");

                    b.Property<short>("HintsUsed")
                        .HasColumnType("smallint")
                        .HasColumnName("hints_used");

                    b.Property<bool>("IsClean")
                        .HasColumnType("boolean")
                        .HasColumnName("is_clean");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("mode");

                    b.Property<short>("TotalMistakes")
                        .HasColumnType("smallint")
                        .HasColumnName("total_mistakes");

                    b.Property<short>("TotalStrokes")
                        .HasColumnType("smallint")
                        .HasColumnName("total_strokes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_writing_attempts");

                    b.HasIndex("ClientAttemptId")
                        .IsUnique()
                        .HasDatabaseName("ux_writing_attempts_client_attempt_id");

                    b.HasIndex("Hanzi")
                        .HasDatabaseName("ix_writing_attempts_hanzi");

                    b.HasIndex("UserId", "CompletedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_writing_attempts_user_completed");

                    b.HasIndex("UserId", "Hanzi", "CompletedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_writing_attempts_user_hanzi");

                    b.ToTable("writing_attempts", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_writing_attempts_duration_ms", "duration_ms IS NULL OR duration_ms BETWEEN 0 AND 3600000");

                            t.HasCheckConstraint("ck_writing_attempts_hints_used", "hints_used BETWEEN 0 AND 200");

                            t.HasCheckConstraint("ck_writing_attempts_mode", "mode IN ('guided','recall')");

                            t.HasCheckConstraint("ck_writing_attempts_total_mistakes", "total_mistakes BETWEEN 0 AND 500");

                            t.HasCheckConstraint("ck_writing_attempts_total_strokes", "total_strokes BETWEEN 1 AND 64");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Lessons.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<Guid?>("EditedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("edited_by");

                    b.Property<short>("EstimatedMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)15)
                        .HasColumnName("estimated_minutes");

                    b.Property<string>("Glossary")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("glossary");

                    b.Property<string>("Level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("hsk1")
                        .HasColumnName("level");

                    b.PrimitiveCollection<List<string>>("Objectives")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("objectives")
                        .HasDefaultValueSql("'{}'");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("machine")
                        .HasColumnName("review_status");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("source");

                    b.Property<string>("SourceHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("source_hash")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValue("")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("topic");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_lessons_created_by");

                    b.HasIndex("EditedBy")
                        .HasDatabaseName("ix_lessons_edited_by");

                    b.HasIndex("ReviewedBy")
                        .HasDatabaseName("ix_lessons_reviewed_by");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_lessons_slug");

                    b.HasIndex("Status", "OrderIndex")
                        .HasDatabaseName("ix_lessons_status_order");

                    b.ToTable("lessons", "content", t =>
                        {
                            t.HasCheckConstraint("ck_lessons_estimated_minutes", "estimated_minutes BETWEEN 1 AND 120");

                            t.HasCheckConstraint("ck_lessons_level", "level IN ('hsk1')");

                            t.HasCheckConstraint("ck_lessons_review_status", "review_status IN ('machine','reviewed')");

                            t.HasCheckConstraint("ck_lessons_source", "source IN ('seed','admin')");

                            t.HasCheckConstraint("ck_lessons_status", "status IN ('draft','published','archived')");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Lessons.LessonBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<short>("OrderIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("order_index");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_lesson_blocks");

                    b.HasIndex("LessonId", "OrderIndex")
                        .HasDatabaseName("ix_lesson_blocks_lesson");

                    b.ToTable("lesson_blocks", "content", t =>
                        {
                            t.HasCheckConstraint("ck_lesson_blocks_type", "type IN ('text','dialogue','grammar','tip')");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Lessons.LessonWord", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.Property<short>("OrderIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("order_index");

                    b.HasKey("LessonId", "WordId")
                        .HasName("pk_lesson_words");

                    b.HasIndex("WordId")
                        .HasDatabaseName("ix_lesson_words_word");

                    b.ToTable("lesson_words", "content");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Lessons.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudioText")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("audio_text");

                    b.Property<string>("CorrectOptionId")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("correct_option_id");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("")
                        .HasColumnName("explanation");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<short>("OrderIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("order_index");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("prompt");

                    b.Property<string>("PromptLang")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("prompt_lang");

                    b.Property<string>("PromptPinyin")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("prompt_pinyin");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_quiz_questions");

                    b.HasIndex("LessonId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_quiz_questions_lesson_key");

                    b.HasIndex("LessonId", "OrderIndex")
                        .HasDatabaseName("ix_quiz_questions_lesson");

                    b.ToTable("quiz_questions", "content", t =>
                        {
                            t.HasCheckConstraint("ck_quiz_questions_prompt_lang", "prompt_lang IN ('vi','zh')");

                            t.HasCheckConstraint("ck_quiz_questions_type", "type IN ('single_choice','listen_choice')");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Pinyin.ToneDrillAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<short>("AnsweredTone")
                        .HasColumnType("smallint")
                        .HasColumnName("answered_tone");

                    b.Property<short>("ExpectedTone")
                        .HasColumnType("smallint")
                        .HasColumnName("expected_tone");

                    b.Property<string>("Hanzi")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("hanzi");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<short>("ItemIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("item_index");

                    b.Property<short>("PartIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("part_index");

                    b.Property<short>("ReplayCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("replay_count");

                    b.Property<int?>("ResponseMs")
                        .HasColumnType("integer")
                        .HasColumnName("response_ms");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Syllable")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("syllable");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tone_drill_answers");

                    b.HasIndex("SessionId", "ItemIndex", "PartIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_tone_drill_answers_session_id_item_index_part_index");

                    b.HasIndex("UserId", "ExpectedTone", "AnsweredAt", "PartIndex")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_tone_drill_answers_user_id_expected_tone_answered_at_part_i");

                    b.ToTable("tone_drill_answers", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_tone_drill_answers_answered_tone", "answered_tone BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_tone_drill_answers_expected_tone", "expected_tone BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_tone_drill_answers_item_index", "item_index >= 0");

                            t.HasCheckConstraint("ck_tone_drill_answers_part_index", "part_index IN (0,1)");

                            t.HasCheckConstraint("ck_tone_drill_answers_replay_count", "replay_count BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_tone_drill_answers_response_ms", "response_ms IS NULL OR response_ms BETWEEN 0 AND 600000");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Pinyin.ToneDrillSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_session_id");

                    b.Property<short>("Correct")
                        .HasColumnType("smallint")
                        .HasColumnName("correct");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("Total")
                        .HasColumnType("smallint")
                        .HasColumnName("total");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tone_drill_sessions");

                    b.HasIndex("UserId", "ClientSessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_tone_drill_sessions_user_id_client_session_id");

                    b.HasIndex("UserId", "FinishedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_tone_drill_sessions_user_id_finished_at");

                    b.ToTable("tone_drill_sessions", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_tone_drill_sessions_correct", "correct BETWEEN 0 AND total");

                            t.HasCheckConstraint("ck_tone_drill_sessions_finished_after_started", "finished_at >= started_at");

                            t.HasCheckConstraint("ck_tone_drill_sessions_mode", "mode IN ('listen_tone','tone_pair')");

                            t.HasCheckConstraint("ck_tone_drill_sessions_total", "total BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Srs.SrsCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasDefaultValue("hanzi_to_meaning")
                        .HasColumnName("card_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("Difficulty")
                        .HasColumnType("double precision")
                        .HasColumnName("difficulty");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<DateTime?>("FirstReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_reviewed_at");

                    b.Property<DateOnly?>("FirstReviewedLocalDate")
                        .HasColumnType("date")
                        .HasColumnName("first_reviewed_local_date");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suspended");

                    b.Property<int>("Lapses")
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("lapses");

                    b.Property<DateTime?>("LastReviewAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_review_at");

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reps");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("source");

                    b.Property<double?>("Stability")
                        .HasColumnType("double precision")
                        .HasColumnName("stability");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("state");

                    b.Property<short?>("Step")
                        .HasColumnType("smallint")
                        .HasColumnName("step");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_id");

                    b.HasKey("Id")
                        .HasName("pk_srs_cards");

                    b.HasIndex("WordId")
                        .HasDatabaseName("ix_srs_cards_word_id");

                    b.HasIndex("UserId", "FirstReviewedLocalDate")
                        .HasDatabaseName("ix_srs_cards_user_first_date");

                    b.HasIndex("UserId", "State", "DueAt")
                        .HasDatabaseName("ix_srs_cards_user_state_due")
                        .HasFilter("is_suspended = false");

                    b.HasIndex("UserId", "WordId", "CardType")
                        .IsUnique()
                        .HasDatabaseName("ux_srs_cards_user_word_type");

                    b.ToTable("srs_cards", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_srs_cards_card_type", "card_type IN ('hanzi_to_meaning')");

                            t.HasCheckConstraint("ck_srs_cards_source", "source IN ('path','manual','lesson')");

                            t.HasCheckConstraint("ck_srs_cards_state", "state IN ('new','learning','review','relearning')");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Srs.SrsReviewLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<Guid>("ClientReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_review_id");

                    b.Property<double>("DifficultyAfter")
                        .HasColumnType("double precision")
                        .HasColumnName("difficulty_after");

                    b.Property<double?>("DifficultyBefore")
                        .HasColumnType("double precision")
                        .HasColumnName("difficulty_before");

                    b.Property<DateTime>("DueAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_after");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<double>("ElapsedDays")
                        .HasColumnType("double precision")
                        .HasColumnName("elapsed_days");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<double>("ScheduledDays")
                        .HasColumnType("double precision")
                        .HasColumnName("scheduled_days");

                    b.Property<double>("StabilityAfter")
                        .HasColumnType("double precision")
                        .HasColumnName("stability_after");

                    b.Property<double?>("StabilityBefore")
                        .HasColumnType("double precision")
                        .HasColumnName("stability_before");

                    b.Property<string>("StateAfter")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("state_after");

                    b.Property<string>("StateBefore")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("state_before");

                    b.Property<short?>("StepBefore")
                        .HasColumnType("smallint")
                        .HasColumnName("step_before");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_srs_review_logs");

                    b.HasIndex("ClientReviewId")
                        .IsUnique()
                        .HasDatabaseName("ux_srs_review_logs_client_review_id");

                    b.HasIndex("CardId", "ReviewedAt")
                        .HasDatabaseName("ix_srs_review_logs_card");

                    b.HasIndex("UserId", "LocalDate")
                        .HasDatabaseName("ix_srs_review_logs_user_date");

                    b.ToTable("srs_review_logs", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_srs_review_logs_rating", "rating BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.RolePermission", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_code");

                    b.HasOne("AntFarm.Chinese.Domain.Access.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.UserRole", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Content.WordCharacter", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Content.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_word_characters_characters_character_id");

                    b.HasOne("AntFarm.Chinese.Domain.Content.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_characters_words_word_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.CharacterWritingStats", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Content.Character", null)
                        .WithMany()
                        .HasForeignKey("Hanzi")
                        .HasPrincipalKey("Hanzi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_writing_stats_characters_hanzi");

                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_writing_stats_users_user_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.LearnerSettings", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithOne()
                        .HasForeignKey("AntFarm.Chinese.Domain.Learning.LearnerSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learner_settings_users_user_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.LessonProgress", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Lessons.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_progress_lessons_lesson_id");

                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_progress_users_user_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.QuizAttempt", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Lessons.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_attempts_lessons_lesson_id");

                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_attempts_users_user_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.StudyEvent", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_study_events_users_user_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.WritingAttempt", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Content.Character", null)
                        .WithMany()
                        .HasForeignKey("Hanzi")
                        .HasPrincipalKey("Hanzi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_writing_attempts_characters_hanzi");

                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_writing_attempts_users_user_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Lessons.Lesson", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_lessons_users_created_by");

                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("EditedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_lessons_users_edited_by");

                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_lessons_users_reviewed_by");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Lessons.LessonBlock", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Lessons.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_blocks_lessons_lesson_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Lessons.LessonWord", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Lessons.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_words_lessons_lesson_id");

                    b.HasOne("AntFarm.Chinese.Domain.Content.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_words_words_word_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Lessons.QuizQuestion", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Lessons.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_questions_lessons_lesson_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Pinyin.ToneDrillAnswer", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Pinyin.ToneDrillSession", null)
                        .WithMany("Answers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tone_drill_answers_tone_drill_sessions_session_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Pinyin.ToneDrillSession", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tone_drill_sessions_users_user_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Srs.SrsCard", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_srs_cards_users_user_id");

                    b.HasOne("AntFarm.Chinese.Domain.Content.Word", null)
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_srs_cards_words_word_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Srs.SrsReviewLog", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Srs.SrsCard", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_srs_review_logs_srs_cards_card_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Pinyin.ToneDrillSession", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
