// <auto-generated />
using System;
using AntFarm.Chinese.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AntFarm.Chinese.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChineseDbContext))]
    partial class ChineseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.HasKey("Code")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "access");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_code");

                    b.ToTable("roles", "access");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission_code");

                    b.HasKey("RoleId", "PermissionCode")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionCode")
                        .HasDatabaseName("ix_role_permissions_permission_code");

                    b.ToTable("role_permissions", "access");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("EmailLower")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("email_lower")
                        .HasComputedColumnSql("lower(email)", true);

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("EmailLower")
                        .HasDatabaseName("ix_users_email_lower");

                    b.ToTable("users", "access");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "access");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.StudyEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Correct")
                        .HasColumnType("integer")
                        .HasColumnName("correct");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_study_events");

                    b.HasIndex("UserId", "LocalDate")
                        .HasDatabaseName("ix_study_events_user_id_local_date");

                    b.HasIndex("UserId", "Kind", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_study_events_user_id_kind_occurred_at");

                    b.ToTable("study_events", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_study_events_correct", "correct IS NULL OR (correct >= 0 AND correct <= quantity)");

                            t.HasCheckConstraint("ck_study_events_quantity", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Pinyin.ToneDrillAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<short>("AnsweredTone")
                        .HasColumnType("smallint")
                        .HasColumnName("answered_tone");

                    b.Property<short>("ExpectedTone")
                        .HasColumnType("smallint")
                        .HasColumnName("expected_tone");

                    b.Property<string>("Hanzi")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("hanzi");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<short>("ItemIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("item_index");

                    b.Property<short>("PartIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("part_index");

                    b.Property<short>("ReplayCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("replay_count");

                    b.Property<int?>("ResponseMs")
                        .HasColumnType("integer")
                        .HasColumnName("response_ms");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Syllable")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("syllable");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tone_drill_answers");

                    b.HasIndex("SessionId", "ItemIndex", "PartIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_tone_drill_answers_session_id_item_index_part_index");

                    b.HasIndex("UserId", "ExpectedTone", "AnsweredAt", "PartIndex")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_tone_drill_answers_user_id_expected_tone_answered_at_part_i");

                    b.ToTable("tone_drill_answers", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_tone_drill_answers_answered_tone", "answered_tone BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_tone_drill_answers_expected_tone", "expected_tone BETWEEN 1 AND 4");

                            t.HasCheckConstraint("ck_tone_drill_answers_item_index", "item_index >= 0");

                            t.HasCheckConstraint("ck_tone_drill_answers_part_index", "part_index IN (0,1)");

                            t.HasCheckConstraint("ck_tone_drill_answers_replay_count", "replay_count BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_tone_drill_answers_response_ms", "response_ms IS NULL OR response_ms BETWEEN 0 AND 600000");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Pinyin.ToneDrillSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_session_id");

                    b.Property<short>("Correct")
                        .HasColumnType("smallint")
                        .HasColumnName("correct");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("Total")
                        .HasColumnType("smallint")
                        .HasColumnName("total");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tone_drill_sessions");

                    b.HasIndex("UserId", "ClientSessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_tone_drill_sessions_user_id_client_session_id");

                    b.HasIndex("UserId", "FinishedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_tone_drill_sessions_user_id_finished_at");

                    b.ToTable("tone_drill_sessions", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_tone_drill_sessions_correct", "correct BETWEEN 0 AND total");

                            t.HasCheckConstraint("ck_tone_drill_sessions_finished_after_started", "finished_at >= started_at");

                            t.HasCheckConstraint("ck_tone_drill_sessions_mode", "mode IN ('listen_tone','tone_pair')");

                            t.HasCheckConstraint("ck_tone_drill_sessions_total", "total BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.RolePermission", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_code");

                    b.HasOne("AntFarm.Chinese.Domain.Access.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Access.UserRole", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Learning.StudyEvent", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_study_events_users_user_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Pinyin.ToneDrillAnswer", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Pinyin.ToneDrillSession", null)
                        .WithMany("Answers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tone_drill_answers_tone_drill_sessions_session_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Pinyin.ToneDrillSession", b =>
                {
                    b.HasOne("AntFarm.Chinese.Domain.Access.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tone_drill_sessions_users_user_id");
                });

            modelBuilder.Entity("AntFarm.Chinese.Domain.Pinyin.ToneDrillSession", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
